version: '3'

services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always

  pgadmin:
    image: pgadmin
    restart: always
